-- 코드를 입력하세요
SELECT
    I_CHILD.ITEM_ID, I_CHILD.ITEM_NAME, I_CHILD.RARITY
FROM
    ITEM_INFO AS I_PARENT
JOIN
    ITEM_TREE AS T ON I_PARENT.ITEM_ID = T.PARENT_ITEM_ID
JOIN
    ITEM_INFO AS I_CHILD ON T.ITEM_ID = I_CHILD.ITEM_ID
WHERE
    I_PARENT.RARITY = 'RARE'
ORDER BY
    I_CHILD.ITEM_ID DESC;